### ISSUE TITLE
Tony Hawk Pro Skater 4

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#48] opened 2022-11-12 04:58 UTC
"You can play, but it can bug out and become all grey screen except HUD" - Blisto

**Comment by WinterSnowfall** [comment] 2023-02-27 16:16
I got the demo and playtested it for about 15 mins, didn't notice any issue in particular, nor the one above. The game might need `d3d9.maxFrameRate = 60`, since the demo at least runs uncapped with VSync off and the physics depends on it being capped. Otherwise, to quote @Blisto91, you're playing Sonic the skateboarder, since everyone will fly around at blazing speed.

The demo executable is called Skate4Demo.exe.

**Comment by WinterSnowfall** [comment] 2023-04-17 09:55
@Blisto91 As the saying goes, "pics or it never happened". I've played with distance fog enabled and haven't been able to reproduce it, but anyway "distance fog" is the first thing one disables in these games (assuming it's not run on a potato).

**Comment by WinterSnowfall** [comment] 2023-04-17 14:23
According to Esdras, who originally reported this, it's no longer reproducible on main, which mirrors my findings. The retail game also seems unaffected by the above 60fps physics problem that the demo had, so we can close this issue.

**Closed as completed** 2023-04-19 08:56 UTC
Labels: bug
