### ISSUE TITLE
Supreme Ruler 2020 - UI and texture flickering

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#130] opened 2023-03-31 17:29 UTC
Another release in this series, another problem (different this time). In the 2020 version of the game, the flickering doesn't go away by setting d3d9.noExplicitFrontBuffer = True. I guess it might be full fledged partial presentation or something else, not entirely sure yet.

WineD3D has a problem of its own: although the 3d graphics all look fine and there's no geometry/texture flickering, there's heavy flickering of text in the UI, to the point where it becomes illegible/outright disappears.

### Software information
Supreme Ruler 2020 (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.89.02
- Wine version: 8.4 Staging
- DXVK version: 2c56a1a

### Apitrace file(s)
[SupremeRuler2020GC.trace.tar.xz](https://drive.google.com/file/d/1oZiHJye-CSdaWtfVYJM60Ow-X4a1sMMY/view?usp=share_link)

### Log files
- d3d8.log: [SupremeRuler2020GC_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11124393/SupremeRuler2020GC_d3d8.log)

**Comment by dungeon007** [comment] 2023-04-02 06:02
Looks OK on NINE and DGV2.
Searching around, it may look correct if you enable nvidia workaround on in menu... but there are also reports of this running slugish, so.

**Comment by WinterSnowfall** [comment] 2023-04-02 09:26
> Searching around, it may look correct if you enable nvidia workaround on in menu... but there are also reports with this enabled it is running more sluggish, so YMMV.

That does indeed fix the flickering, on both Nvidia and Intel, and both with d8vk and WineD3D. 

Unfortunately, with this game-provided workaround enabled, it looks like it relies on driver behavior to optimize away certain operations it is doing, such as an insane number of draw calls on certain map zoom levels. I believe it is doing one draw call per map hex, which sometimes ends up in the range of 70000 per frame :astonished:. This will be a tough nut to crack...

While investigating further I also noticed the game will frequently crash when switching between zoom levels without a memory limit in place, so at least I'll PR that part.

**Comment by WinterSnowfall** [comment] 2023-04-02 10:34
I've closed my PR, as it doesn't actually help a lot (I was tricked into thinking it helped because it sort of worked when I was tracing at the same time). The game will simply run out of address space when hitting those ridiculously high draw call numbers (see https://github.com/doitsujin/dxvk/issues/3115 for a similar problem). Performance is actually not that bad all things considered, so if we can figure out a way to prevent crashing here, that would be nice.

Or, if we could figure out a way to prevent the flickering without resorting to the in-game workaround that would be even better, as I haven't seen it do more than 2.2K draw calls per frame in this case, which is a lot more tame.

**Comment by WinterSnowfall** [comment] 2023-04-13 15:50
`d3d9.allowDirectBufferMapping = False` makes the game behave in a similar fashion as with WineD3D, which I'm not sure is a step in the right direction. The vertex flickering is gone, but all rendered text blinks in and out of existence. How this game ever worked on native is a bit of a mystery at this point...

**Comment by AlpyneDreams** [comment] 2023-04-15 03:01
> `d3d9.allowDirectBufferMapping = False` makes the game behave in a similar fashion as with WineD3D, which I'm not sure is a step in the right direction. The vertex flickering is gone, but all rendered text blinks in and out of existence. How this game ever worked on native is a bit of a mystery at this point...

Can you get a trace with that setting? It seems like the game is trying to draw nonsense vertex data from an offset really deep into the vertex buffer for drawing UI stuff and I'm not sure why.

**Comment by AlpyneDreams** [comment] 2023-04-15 07:31
It's locking the correct offset and size for the drawcall it makes, but it uses D3DLOCK_NOOVERWRITE.

It seems there is a subtle difference in the d3d8 and d3d9 docs because d3d8 docs say "no vertices that were referred to in drawing calls since the start of the frame or the last lock without this flag will be modified" but d3d9 says "memory that was referred to in a drawing call since the last lock without this flag will not be modified." 

So perhaps the application is expecting d3d8 to preserve some data it already used since the start of the frame. Indeed, there are many many many uses of the buffer in this frame (421)... So the application is getting buffers that are in-use immediately that it expects to wait for, and therefore messing up its drawcalls.

So for now I have disabled D3DLOCK_NOOVERWRITE. It's not really that important when there's not a lot of vertex data.

**Comment by AlpyneDreams** [comment] 2023-04-15 07:33
As for the text flickering, I haven't figured that one out yet.

**Comment by WinterSnowfall** [comment] 2023-04-15 08:32
> So for now I have disabled D3DLOCK_NOOVERWRITE. It's not really that important when there's not a lot of vertex data.

Some games seem to use D3DLOCK_NOOVERWRITE incorrectly anyway, such as Commandos 3. Not sure what native is actually doing in these cases, but there doesn't seem to be any validation happening on VBs created with D3DUSAGE_WRITEONLY at least.

We'll have to see if anything regresses on this performance-wise (I hope not?), in which case using `d3d9.allowDirectBufferMapping = False` here has the same functional outcome.

> As for the text flickering, I haven't figured that one out yet.

Yeah, that's the only issue left even with `d3d9.allowDirectBufferMapping = False` in place.

**Comment by AlpyneDreams** [comment] 2023-04-15 13:39
> We'll have to see if anything regresses on this performance-wise (I hope not?), in which case using `d3d9.allowDirectBufferMapping = False` here has the same functional outcome.

- [x] Good idea. I suppose it depends of this fixes any other games or not.
- [ ] We'll see if the text thing is related.

**Comment by WinterSnowfall** [comment] 2023-04-15 13:42
>     * [ ]  Good idea. I suppose it depends of this fixes any other games or not.

I believe it should also fix at least Commandos 3. In that the workaround we've just added for it shouldn't be needed now. But I haven't tested this to confirm, it just makes sense.

**Comment by AlpyneDreams** [comment] 2023-04-15 14:13
> I believe it should also fix at least Commandos 3. In that the workaround we've just added for it shouldn't be needed now. But I haven't tested this to confirm, it just makes sense.

I mean disabling NOOVERWRITE. I think it's the more correct solution for now since disabling direct buffer mapping is case-by-case and just kind of sidesteps the issue.

**Comment by AlpyneDreams** [comment] 2023-04-16 02:17
> I mean disabling NOOVERWRITE. I think it's the more correct solution for now since disabling direct buffer mapping is case-by-case and just kind of sidesteps the issue.

Nevermind, terrible idea. Reverting.

**Comment by AlpyneDreams** [comment] 2023-04-16 03:03
A little more investigation:
- The vertex buffer is DYNAMIC
- With d9vk and d3d8to9 ([which does nothing to prevent this](https://github.com/crosire/d3d8to9/blob/4cfb67b17ba983262fe1eae47fc96cc198ca921c/source/d3d8to9_vertex_buffer.cpp#L100)) the red thing is present and flickering
- Disabling direct buffer mapping for this game produces the same results as the NOOVERWRITE thing so I think that's a good idea. See #135 
- Switching default pool buffers to managed pool also fixes things and may result in better perf. See #135 again

**Comment by dungeon007** [comment] 2023-04-16 04:01
>     * With d9vk and d3d8to9 ([which does nothing to prevent this](https://github.com/crosire/d3d8to9/blob/4cfb67b17ba983262fe1eae47fc96cc198ca921c/source/d3d8to9_vertex_buffer.cpp#L100)) the red thing is present and flickering

 Put a line somthing like `if (Pool == D3DPOOL_DEFAULT) Pool = D3DPOOL_MANAGED;`
 At https://github.com/crosire/d3d8to9/blob/main/source/d3d8to9_device.cpp#L305

 Try to run that on D3D9 DXVK 1.8.1 where this behave fine by default (not nvidia workaround nedded)... and then observe how 1.9 breaks this, probably with these too much optimizations like "Improved texture and buffer uploads in D3D9."

 Same way for 3DMark2001 High Detail tests... but now for an index instead of vertex
 https://github.com/crosire/d3d8to9/blob/main/source/d3d8to9_device.cpp#L322
 And for that Water test from D3D8 samples, it is also index.

**Comment by AlpyneDreams** [comment] 2023-04-16 05:36
@dungeon007 
> Put a line something like `if (Pool == D3DPOOL_DEFAULT) Pool = D3DPOOL_MANAGED;` At https://github.com/crosire/d3d8to9/blob/main/source/d3d8to9_device.cpp#L305
> 
> Now try to run that on D3D9 DXVK 1.8.1 where this looks fine by default (not nvidia workaround nedded)... and then observe how DXVk 1.9 breaks this, probably with these too much optimizations like "Improved texture and buffer uploads in D3D9." Do anybody even needs these improved buffer uploads for D3D8? Probably not, instead you probably want to avoid that.

How is it broken? Does the same issue exist in D3D9 from DXVK 2.1?

Also, Make sure you also do `Usage &= D3DUSAGE_DYNAMIC;` after setting the pool to MANAGED or else you may hit unexpected behavior since those aren't compatible.

> Same way for 3DMark2001 High Detail tests... but now force it for index instead of vertex https://github.com/crosire/d3d8to9/blob/main/source/d3d8to9_device.cpp#L322 And for that Water test from D3D8 samples, it is also index. Should bump up perf. But forcing Index does not seem to be affected, so you dont have to go back.
>
> Or if you holding always both into managed sound perfect and should prevent any memory leaks... problem is, that is not always good for performance, and/or it may behave different on different drivers, apps or so... forcing nothing is a best default. It is probably a problematic app, or just wrappers arent so great optimized by default, if it needs such forces. "How this game ever worked on native is a bit of a mystery at this point..." Well, drivers were likely different and differently optimized back then too... hitting different paths, faster or slower.

We are considering storing both index and vertex buffers that are in the default pool as managed on the D3D9-side (with maybe minor exceptions like WRITEONLY). Since dxvk doesn't have to deal with differing drivers like on d3d8to9 does this should be fine.

**Comment by dungeon007** [comment] 2023-04-16 05:39
"How is it broken? Does the same issue exist in D3D9 from DXVK 2.1?"
Yes, with a forced vertex in a managed pool, this only looks fine on DXVX 1.8.1... while since DXVK 1.9 glitches continues regraless of force, including 2.1 of course.

**Comment by AlpyneDreams** [comment] 2023-04-16 05:55
@dungeon007 
> "How is it broken? Does the same issue exist in D3D9 from DXVK 2.1?" Sure, with a forced vertex in a managed pool, this only looks fine by default on DXVK 1.8.1... while as i see since DXVK 1.9 glitches continues regardless of force, including 2.1 of course. That on RADV, maybe it is different on NVIDIA. I am never sure what happens with different drivers.

What GPU do you have? I'm on NVIDIA so I can't properly assess if it's broken or not.

How about the [latest build of d8vk](https://github.com/AlpyneDreams/d8vk/actions/runs/4711724934) where everything is managed. Are you seeing glitching with that? Take a screenshot with DXVK_HUD=full if possible.

**Comment by dungeon007** [comment] 2023-04-16 06:04
It is the same glitchy with that too.

**Comment by AlpyneDreams** [comment] 2023-04-16 06:08
> "How about the [latest build of d8vk](https://github.com/AlpyneDreams/d8vk/actions/runs/4711724934) where everything is managed." It is the same glitchy with that too.

A screenshot with the full HUD would be appreciated so I can figure out which of the multiple issues this game has is happening here. Just set `DXVK_HUD=full` and take one. Thanks :)

**Comment by AlpyneDreams** [comment] 2023-04-16 06:23
@dungeon007 Thanks. That looks like the text issue which is a separate issue to the flickering. Do things stay the same or get worse if you use [this build](https://github.com/AlpyneDreams/d8vk/actions/runs/4710971890) where things aren't managed? (No screenshot needed this time)

**Comment by dungeon007** [comment] 2023-04-16 06:33
It is not the same flicker of course, with that one text stops flickering, but game flickers. And the opposite, with previous one.

**Comment by AlpyneDreams** [comment] 2023-04-16 06:34
> It is not the same flicker of course, with that one text stops flickering, but game flickers. And the opposite, with previous one.

Does the text look perfect or is it missing some characters? Or does that depend on if you enable the nvidia fix in the menu?

**Comment by dungeon007** [comment] 2023-04-16 06:42
With nvidia fix, it works, but slow and sluggish.
Sometimes so slugish, that i am better running this on a pure CPU :D

**Comment by AlpyneDreams** [comment] 2023-04-16 06:46
> 

Right, interesting. Looking into the text issue now. It seems like a weird one.

**Comment by WinterSnowfall** [comment] 2023-04-16 06:56
[Here's a trace captured with the Nvidia workaround enabled](https://drive.google.com/file/d/1QaDItfp8LDqYfRj1FWxbASo_C88RHhL4/view?usp=share_link), captured with WineD3D. I'm toggling it on and off in the menu at the start, so it's more obvious what fixes the broken text. I've also gone in game and switched through various zoom levels so you can ascertain performance.

**Comment by dungeon007** [comment] 2023-04-16 08:09
You have some options in registry too, like UseVideofix (that seems to be nVidia workaround in menu), UseHWVertex, UseAlwaysdraw...
That also sounds like might change something, to flicker or not differently on a different drivers :D

**Comment by AlpyneDreams** [comment] 2023-04-22 04:20
This game should be fixed as of cd5b89b8b4696a29b23b2a954cb00a6c9c26cff0. You should leave NVIDIA Driver Workaround disabled now.

**Closed as completed by AlpyneDreams** 2023-04-22 04:20 UTC
Labels: bug
