### ISSUE TITLE
Bloodrayne performance down so much with lastest git

### ISSUE THREAD

**Issue by mrdeathjr28** [AlpyneDreams/d8vk#136] opened 2023-04-15 19:06 UTC
Hi

Blood rayne performace go down seriously with lastest git

![br1ops](https://user-images.githubusercontent.com/6601480/232248771-8d9f12b1-4950-4887-9c2a-12f5eda45440.png)

and with before versions works ok

![br1bfrops](https://user-images.githubusercontent.com/6601480/232248800-5f46c17e-e790-4251-8764-442334719848.png)

![blrbfropsa](https://user-images.githubusercontent.com/6601480/232248808-da80495d-7aad-479a-b1e6-e830f9011a71.png)

update bloodrayne 2 stay affected too

![br2ops](https://user-images.githubusercontent.com/6601480/232249046-61bb8fe7-d600-4cd6-8d47-efdb535e27d1.png)

**Comment by WinterSnowfall** [comment] 2023-04-15 19:13
Thank you for the report. We are aware of the regression (it was caused by 9774d48) and it should be fixed shortly.

**Comment by AlpyneDreams** [comment] 2023-04-16 02:35
Fixed in abbd257911eefd733ae9d6760990739807f63f16.

@mrdeathjr28 is it good now?

**Comment by mrdeathjr28** [comment] 2023-04-16 03:55
> Fixed in [abbd257](https://github.com/AlpyneDreams/d8vk/commit/abbd257911eefd733ae9d6760990739807f63f16).
> 
> @mrdeathjr28 is it good now?

yeah with this performance are fixed

**Comment by AlpyneDreams** [comment] 2023-04-16 05:40
Great.

**Closed as completed by AlpyneDreams** 2023-04-16 05:40 UTC
