### ISSUE TITLE
Rise of Nations shadow blending glitch

### ISSUE THREAD

**Issue by imamhs** [AlpyneDreams/d8vk#157] opened 2023-05-11 15:29 UTC
The game starts and runs fine, graphics looks alright except there is shadow blending issues compared to WineD3D and Windows D3D. Please see attached screen-grab. 

**System information**

- GPU: AMD RX 6600 XT
- Driver: Mesa3D 23.0.3
- Wine version: 8.6
- DXVK version: d8vk-v1.0 (commit https://github.com/AlpyneDreams/d8vk/commit/e1df54ceaa4bdae12124ce4e638bccf641a34fa6)

**Log files**

- nations_d3d8.log:

info:  Game: nations.exe
info:  DXVK: v1.7.1-2160-g10cbd551
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x6fa83800
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  AMD Radeon RX 6600 XT (RADV NAVI23):
info:    Driver: 23.0.3
info:    Vulkan: 1.3.238
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[7]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 7957 MiB
info:      Flags: 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[5]: Property Flags = 0xe
info:      Memory Type[6]: Property Flags = 0xe
info:      Memory Type[8]: Property Flags = 0xc6
info:      Memory Type[10]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[3]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0x7
info:      Memory Type[9]: Property Flags = 0xc7
info:  Process set as DPI aware
info:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  AMD Radeon RX 6600 XT (RADV NAVI23):
info:    Driver: 23.0.3
info:    Vulkan: 1.3.238
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[7]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 7957 MiB
info:      Flags: 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[5]: Property Flags = 0xe
info:      Memory Type[6]: Property Flags = 0xe
info:      Memory Type[8]: Property Flags = 0xc6
info:      Memory Type[10]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[3]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0x7
info:      Memory Type[9]: Property Flags = 0xc7
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : AMD Radeon RX 6600 XT (RADV NAVI23)
info:    Driver version   : 23.0.3
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_attachment_feedback_loop_layout
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state3
info:    VK_EXT_memory_priority
info:    VK_EXT_non_seamless_cube_map
info:    VK_EXT_robustness2
info:    VK_EXT_shader_module_identifier
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_pipeline_library
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 0
info:    shaderResourceMinLod                   : 0
info:    sparseBinding                          : 0
info:    sparseResidencyBuffer                  : 0
info:    sparseResidencyImage2D                 : 0
info:    sparseResidencyImage3D                 : 0
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 0
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 0
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 0
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 1
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 1
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state3
info:    extDynamicState3AlphaToCoverageEnable  : 1
info:    extDynamicState3DepthClipEnable        : 1
info:    extDynamicState3RasterizationSamples   : 1
info:    extDynamicState3SampleMask             : 1
info:  VK_EXT_fragment_shader_interlock
info:    fragmentShaderSampleInterlock          : 0
info:    fragmentShaderPixelInterlock           : 0
info:  VK_EXT_full_screen_exclusive
info:    extension supported                    : 0
info:  VK_EXT_graphics_pipeline_library
info:    graphicsPipelineLibrary                : 0
info:  VK_EXT_memory_budget
info:    extension supported                    : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_module_identifier
info:    shaderModuleIdentifier                 : 1
info:  VK_EXT_shader_stencil_export
info:    extension supported                    : 1
info:  VK_EXT_swapchain_colorspace
info:    extension supported                    : 0
info:  VK_EXT_hdr_metadata
info:    extension supported                    : 0
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_external_memory_win32
info:    extension supported                    : 0
info:  VK_KHR_external_semaphore_win32
info:    extension supported                    : 0
info:  VK_NVX_binary_import
info:    extension supported                    : 0
info:  VK_NVX_image_view_handle
info:    extension supported                    : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:    Sparse   : 0
info:  DXVK: Read 50 valid state cache entries
info:  DXVK: Graphics pipeline libraries not supported
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1024
info:      - Height:             768
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D16
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 0
info:  Setting display mode: 1024x768@0
info:  Setting display mode: 1024x768@0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1024x768
info:    Image count:  4
info:    Exclusive FS: 0
info:  DXVK: Using 12 compiler threads
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1024x768
info:    Image count:  4
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1024x768
info:    Image count:  4
info:    Exclusive FS: 0

**Screenshot of the glitch (d8vk, shadow squares instead of smooth blending):**
![d8vk](https://github.com/AlpyneDreams/d8vk/assets/10392833/a9639c6e-46d0-4338-9468-b337117a990e)

**Screenshot of the normal rendering as in WineD3D:**
![WineD3D](https://github.com/AlpyneDreams/d8vk/assets/10392833/41f2ee0f-8796-4eb3-abcd-ec102aee4176)

**Comment by WinterSnowfall** [comment] 2023-05-11 15:46
It's fixed by `d3d8.managedBufferPlacement = False`. I'll include it in my regression PR :).

![RiseOfNations](https://github.com/AlpyneDreams/d8vk/assets/6306593/992097b0-b0ae-4d32-8ac1-5ad2e9ca67ef)

Thanks for the report! ~~I didn't test this again because it doesn't launch in newer versions of Wine, but I rolled back to confirm.~~ Nevermind, I had forgotten to disable esync.

P.S.: Does it look properly in WineD3D for you? Because in my case it looks as broken as it is with d8vk now, same fog of war and terrain glitches. Albeit I use Wine Staging.

**Comment by imamhs** [comment] 2023-05-11 16:00
Thank you!

I confirm it appears to render correctly with vanilla WineD3D 8.6.

With d8vk-v1.0 and d3d8.managedBufferPlacement = False in dxvk.conf the glitch is present and also there is new ground texture glitch as you said it is regression in latest d8vk. Please see below:

![glitch](https://github.com/AlpyneDreams/d8vk/assets/10392833/0166bc3c-af2d-4b70-b493-21900a8cf464)

**Comment by mrdeathjr28** [comment] 2023-05-11 16:04
> Thank you!
> 
> I confirm it appears to render correctly with vanilla WineD3D 8.6.
> 
> With d8vk-v1.0 and d3d8.managedBufferPlacement = False in dxvk.conf the glitch is present and also there is new ground texture glitch as you said it is regression in latest d8vk. Please see below:
> 
> ![glitch](https://user-images.githubusercontent.com/10392833/237747245-0166bc3c-af2d-4b70-b493-21900a8cf464.png)

In my case pass same thing and game launch ok with wine staging 8.7 for now (cinematics stay in black but is completly different issue)

![ronold](https://github.com/AlpyneDreams/d8vk/assets/6601480/76379f88-632c-48ad-a9b9-4b31711b30e2)

**Comment by WinterSnowfall** [comment] 2023-05-11 16:05
> With d8vk-v1.0 and d3d8.managedBufferPlacement = False in dxvk.conf the glitch is present and also there is new ground texture glitch as you said it is regression in latest d8vk.

Not really sure what you mean here. `d3d8.managedBufferPlacement = False` fixed all glitches in my case. It should look good once you add that. Let me add it to my PR and you can test with that.

**Comment by mrdeathjr28** [comment] 2023-05-11 16:08
tested with d3d8.managedBufferPlacement = False and appears this:

![ronolda](https://github.com/AlpyneDreams/d8vk/assets/6601480/f996e2c8-a525-41b9-88d6-2e57451d68aa)

**Comment by WinterSnowfall** [comment] 2023-05-11 16:28
![image](https://github.com/AlpyneDreams/d8vk/assets/6306593/4041bec7-c1c6-41f2-a091-abd7a516909f)

This is what I am seeing with the latest builds on my PR, on Nvidia: https://github.com/AlpyneDreams/d8vk/actions/runs/4950102988

Everything appears correct. I'm not ruling out a problem in Mesa, but I can't reproduce any fog of war or terrain glitch any more.

The game has always worked correctly for me, even with d8vk 0.10. Using `d3d8.managedBufferPlacement = False` lets the game do its own buffer placement, which should be the most compatible if a game behaves correctly with buffers.

Could you please retest with the above artifacts one more time?

**Comment by WinterSnowfall** [comment] 2023-05-11 16:54
![image](https://github.com/AlpyneDreams/d8vk/assets/6306593/73d6ad97-4f36-49ac-aa55-110238e58bb3)

Here is a screenshot of my PR on (almost) latest ANV (Laptop with an Intel Xe iGPU).

**Comment by imamhs** [comment] 2023-05-11 17:06
> ![image](https://user-images.githubusercontent.com/6306593/237760148-73d6ad97-4f36-49ac-aa55-110238e58bb3.png)
> 
> Here is a screenshot of my PR on (almost) latest ANV (Laptop with an Intel Xe iGPU).

Which Wine version are you using? I have tried both amdvlk and radv vulkan drivers still the same issue with the latest builds (https://github.com/AlpyneDreams/d8vk/actions/runs/4950102988)

**Comment by WinterSnowfall** [comment] 2023-05-11 17:09
> Which Wine version are you using?

8.7 Staging. Unfortunately I don't have an AMD GPU to check against.

**Comment by dungeon007** [comment] 2023-05-11 17:24
Maybe app have vendor specific rendering paths.
Something like with Age of Mythology, so it acutlly renderers differently on different GPUs/drivers.

**Comment by imamhs** [comment] 2023-05-11 17:33
Only way to now verify this is a Mesa3D and driver specific issue to test on another machine with a nvidia card

**Comment by WinterSnowfall** [comment] 2023-05-11 17:51
Could be some other factors at play here as well. But it's weird it appears to work fine both on Nvidia and Intel in my case.

**Comment by mrdeathjr28** [comment] 2023-05-11 21:15
Sadly Xe based gpu are different than pre xe gpus

However add trace:

https://drive.google.com/file/d/1Y7ZIJ2kYvkEpn3WLrVikuPy8GF8ulYYM/view?usp=sharing

**Comment by imamhs** [comment] 2023-05-12 02:34
> > Which Wine version are you using?
> 
> 8.7 Staging. Unfortunately I don't have an AMD GPU to check against.

Are you using 64bit version of d8vk (d3d8.dll)? I tried to run the game using 64 bit Wine prefix where Wine avoids using 32 bit d8vk (d3d8.dll)

**Comment by mrdeathjr28** [comment] 2023-05-12 04:35
> > > Which Wine version are you using?
> > 
> > 
> > 8.7 Staging. Unfortunately I don't have an AMD GPU to check against.
> 
> Are you using 64bit version of d8vk (d3d8.dll)? I tried to run the game using 64 bit Wine prefix where Wine avoids using 32 bit d8vk (d3d8.dll)

In my case works but on staging with all packages installed aka:

wine-staging-i386_8.7~lunar-1_i386.deb

wine-staging-amd64_8.7~lunar-1_amd64.deb

wine-staging_8.7~lunar-1_amd64.deb

winehq-staging_8.7~lunar-1_amd64.deb

Last package allows use 32bit apps also 64bit in same prefix without troubles and d8vk is a 32bit library because DX8 games are 32bit

**Comment by WinterSnowfall** [comment] 2023-05-12 05:50
> Are you using 64bit version of d8vk (d3d8.dll)? 

As mrdeathjr28 said, there is no such thing. The d3d8.dll packaged by d8vk is 32-bit only.

> I tried to run the game using 64 bit Wine prefix where Wine avoids using 32 bit d8vk (d3d8.dll)

I have the game in a 64-bit prefix and it works perfectly with d8vk. You can either use the install script or manually replace Wine's dll in syswow64 and add a Wine native dll override for d3d8. 

On a side-note, Wine will always load what the application requests, regardless of what type of prefix you are in, just like Windows. In case of 32-bit applications, it will load 32-bit dlls. The fact that Wine now uses thunks to end up into 64-bit code is transparent to the end application (from its standpoint 32-bit dlls have been loaded). This has not changed.

**Comment by dungeon007** [comment] 2023-05-12 13:26
Tried demo and indeed i could reproduce an issue.
Happen also with d3d8to9 + d3d9 dxvk. WINED3D, DGV2, NINE are fine there. 
dxvk 1.8.1 not a bug, with dxvk 1.9 bug starts to appear... so these "Improved texture and buffer uploads in D3D9." again.
So reminds me on Supreme Ruler 2020 flickering, guessing that might need some sort of integer value like there, instead of just true/false.

**Comment by WinterSnowfall** [comment] 2023-05-12 13:32
> Tried demo and indeed i could reproduce an issue on AMD.

Thank you for retesting. Were you able to give it a go on anything other than AMD, to confirm if this is maybe only AMD specific?

**Comment by dungeon007** [comment] 2023-05-12 13:40
No, curretly. But i also tried forcing different vendors with NINE and DGV2, but it do not look like to be vendor isssue.
It does not happen using anything else, even DGV2/DX11/DXVK... only shows up on VK D3D9 part, since dxvk 1.9.

**Comment by WinterSnowfall** [comment] 2023-05-12 13:44
Alright, no worries. It's still very surprising that I can't reproduce this in any way with my PR that sets `d3d8.managedBufferPlacement = False`. I have also tried switching vendors to AMD and it still looks good.

**Comment by WinterSnowfall** [comment] 2024-07-07 14:14
@imamhs @dungeon007 Can you please try to see if this is still a problem with dxvk master? We're now upstream.

**Comment by mrdeathjr28** [comment] 2024-07-07 19:22
in my case issues are fixed with lastest master

![d8vka](https://github.com/AlpyneDreams/d8vk/assets/6601480/12b327d7-e39c-4bda-9b47-c76a01908f3b)

**Comment by WinterSnowfall** [comment] 2024-07-07 20:04
@Blisto91 has also confirmed this looks fine now on master. Not sure what it was all about, but we can close this issue.

**Comment by mrdeathjr28** [comment] 2024-07-07 20:06
> @Blisto91 has also confirmed this looks fine now on master. Not sure what it was all about, but we can close this issue.

also fix heavy stutter in billy hatcher and the giant egg in my case

**Closed as completed** 2024-07-09 16:44 UTC
Labels: bug
