### ISSUE TITLE
BorderZone - CopyRects issues with shadows enabled

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#102] opened 2023-02-03 08:29 UTC
The game runs into some issues when enabling shadows:
![BorderZoneShadowsOn](https://user-images.githubusercontent.com/6306593/216549229-d8a67d16-d5fd-4bab-9435-f9ae76753296.png)

This is how it should normally look:
![BorderZoneSOFF](https://user-images.githubusercontent.com/6306593/216549319-0d06b2c1-f7e8-4b88-979e-e33f3c88f519.png)

The problems seems to be cause by some limitations in CopyRects:
`debug: CopyRects: FAILED to copy from src pool 1 to dst pool 1`

The game crashed when attempting to trace with d3d8, but I was able to at least get a trace with d3d8to9 and WineD3D, though that might not be so useful for debugging CopyRects.

### Software information
BorderZone (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.78.01
- Wine version: 7.22 Staging
- DXVK version: f4988e7

### Apitrace file(s)
[borderzone.trace.tar.xz](https://drive.google.com/file/d/1uIXcghMoGJHd21hTEX9p_hooECKZN2gA/view?usp=share_link)

### Log files
- d3d8.log: [borderzone_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10577026/borderzone_d3d8.log)
- d3d9.log: [borderzone_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10577027/borderzone_d3d9.log)

**Comment by WinterSnowfall** [comment] 2023-02-05 17:30
Apparently this is also fixed by uncommenting:

```
        // FIXME: Doing this crashes a GTA Vice City trace
        // and possibly other things too. Investigate.
        m_renderTarget = ref(surf);
```

![Shadows](https://user-images.githubusercontent.com/6306593/216835036-f54172fe-5b2f-420d-9a8f-3061fd5f32db.png)

Since you've mentioned this will break GTA Vice City though, I won't PR anything until we can figure out what's the problem with that game, but there are already two games that are relying on this to be in place (see #98), and I'm assuming there could be even more.

If this weren't simply a ref, I'd suggest we put a config option in place to work around GTA: VC and any other games that it breaks, but here it just sounds like a dumb thing to do.

**Comment by AlpyneDreams** [comment] 2023-02-24 05:10
So the ref thing was fixed by 567b0335bdc55e201b0cab825845f4e3ea75b0f1, but now there appears to be a new issue (possibly a regression) with meshes not showing up in the trace. Investigating now.

**Comment by AlpyneDreams** [comment] 2023-02-24 05:18
Hmm, this could be an issue with the trace being a WineD3D trace. It happens on both d0f590323ca7f12fc70349dd9689bab0739b4d3e and f4988e73e90a6e006860843e0a452c25d852bb38, even without yesterday's rebase.

**Comment by AlpyneDreams** [comment] 2023-02-24 05:20
Yeah, actually, the trace looks like that even when replayed with WineD3D.

**Comment by AlpyneDreams** [comment] 2023-02-24 05:20
@WinterSnowfall If you can confirm that the game runs fine now then I'll close this issue.

**Closed as completed** 2023-02-24 06:48 UTC
Labels: bug
